[package]
name = "cpp-interop"
version = "0.1.0"
edition = "2021"
default-run = "cpp-interop"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cpp-interop"
path = "src/cpp-interop.rs"

[dependencies]
