[package]
name = "big-O"
version = "0.1.0"
edition = "2018"
default-run = "big-o"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "big-o"
path = "src/big-o.rs"

[dependencies]

[dev-dependencies]
serial_test = "0.5"